version: '3'
services:
  mysql_master_1:
    image: mysql:8.0
    env_file:
      - ./master/mysql_master.env
    container_name: "mysql_master_1"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./master/data:/var/lib/mysql
    networks:
      - overlay

  mysql_master_2:
    image: mysql:8.0
    env_file:
      - ./slave/mysql_slave.env
    container_name: "mysql_master_2"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - mysql_master_1
    volumes:
      - ./slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./slave/data:/var/lib/mysql
    networks:
      - overlay

networks:
  overlay:

